[build]
command = "npm run build"  # Your build command
publish = "build"          # Directory where your build output is stored
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = true
